import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../data/claude_question_service.dart';
import '../../data/seeded_questions.dart';
import '../../data/wikipedia_service.dart';
import '../../domain/models/question.dart';
import '../../domain/models/room.dart';
import 'game_state_provider.dart';

// ---------------------------------------------------------------------------
// Question mode
// ---------------------------------------------------------------------------

enum QuestionMode {
  /// Live questions generated by Wikipedia + Claude API.
  api,

  /// Hardcoded questions shipped with the app — no API key needed.
  seeded,
}

/// Whether the app has a non-empty Anthropic API key available.
final questionModeProvider = Provider<QuestionMode>((ref) {
  final key = dotenv.env['ANTHROPIC_API_KEY'] ?? '';
  return key.isNotEmpty ? QuestionMode.api : QuestionMode.seeded;
});

// ---------------------------------------------------------------------------
// Service providers (overridable in tests)
// ---------------------------------------------------------------------------

final wikipediaServiceProvider = Provider<WikipediaService>(
  (ref) => WikipediaService(),
);

final claudeQuestionServiceProvider = Provider<ClaudeQuestionService>(
  (ref) => ClaudeQuestionService(
    apiKey: dotenv.env['ANTHROPIC_API_KEY'] ?? '',
  ),
);

// ---------------------------------------------------------------------------
// Question provider
// ---------------------------------------------------------------------------

final questionProvider =
    AsyncNotifierProvider<QuestionNotifier, Question?>(QuestionNotifier.new);

class QuestionNotifier extends AsyncNotifier<Question?> {
  @override
  Future<Question?> build() async => null;

  Future<void> fetchQuestion(RoomTheme theme) async {
    state = const AsyncValue.loading();

    final mode = ref.read(questionModeProvider);

    if (mode == QuestionMode.seeded) {
      await _loadSeeded(theme);
    } else {
      await _fetchFromApi(theme);
    }
  }

  /// Returns the hardcoded question for this room instantly.
  Future<void> _loadSeeded(RoomTheme theme) async {
    // Small delay so the loading skeleton is visible (better UX than instant flash)
    await Future.delayed(const Duration(milliseconds: 600));

    final question = seededQuestions[theme.id];
    if (question == null) {
      // Should never happen — every room has a seeded question
      state = AsyncValue.error(
        Exception('No seeded question for room "${theme.id}"'),
        StackTrace.current,
      );
      return;
    }
    state = AsyncValue.data(question);
    ref.read(gameStateProvider.notifier).markPlaying();
  }

  /// Calls Wikipedia → Claude pipeline; falls back to seeded on failure.
  Future<void> _fetchFromApi(RoomTheme theme) async {
    final wikipedia = ref.read(wikipediaServiceProvider);
    final claude = ref.read(claudeQuestionServiceProvider);
    final usedTitles = ref.read(gameStateProvider).usedArticleTitles;

    try {
      final availableTopics = theme.wikiTopics
          .where((t) => !usedTitles.contains(t))
          .toList();
      final topics =
          availableTopics.isNotEmpty ? availableTopics : theme.wikiTopics;

      final article = await wikipedia.fetchArticleSummary(topics);
      ref.read(gameStateProvider.notifier).addUsedArticle(article.title);

      final question = await claude.generateQuestion(article);
      state = AsyncValue.data(question);
      ref.read(gameStateProvider.notifier).markPlaying();
    } catch (_) {
      // API failed — silently fall back to the seeded question for this room
      await _loadSeeded(theme);
    }
  }

  void reset() {
    state = const AsyncValue.data(null);
  }
}
