import 'package:flutter/material.dart';
import '../../../../core/theme/app_theme.dart';
import '../providers/question_provider.dart';

class RoomHeader extends StatelessWidget implements PreferredSizeWidget {
  final String roomName;
  final int score;
  final int lives;
  final QuestionMode mode;

  const RoomHeader({
    super.key,
    required this.roomName,
    required this.score,
    required this.lives,
    required this.mode,
  });

  @override
  Size get preferredSize => const Size.fromHeight(kToolbarHeight);

  @override
  Widget build(BuildContext context) {
    final textTheme = Theme.of(context).textTheme;

    return AppBar(
      title: Text(roomName),
      actions: [
        // Mode badge
        _ModeBadge(mode: mode),
        const SizedBox(width: 8),

        // Lives
        Row(
          children: List.generate(
            3,
            (i) => Icon(
              Icons.favorite,
              size: 18,
              color: i < lives ? AppColors.dangerRed : AppColors.stoneMid,
            ),
          ),
        ),
        const SizedBox(width: 10),

        // Score pill
        Container(
          margin: const EdgeInsets.only(right: 16),
          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
          decoration: BoxDecoration(
            color: AppColors.stoneDark,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: AppColors.torchAmber, width: 1),
          ),
          child: Text(
            '$score',
            style: textTheme.labelLarge?.copyWith(
              color: AppColors.torchAmber,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),
      ],
    );
  }
}

class _ModeBadge extends StatelessWidget {
  final QuestionMode mode;

  const _ModeBadge({required this.mode});

  @override
  Widget build(BuildContext context) {
    final isApi = mode == QuestionMode.api;

    return Tooltip(
      message: isApi
          ? 'Live mode: questions generated by Claude AI'
          : 'Classic mode: pre-set questions (no API key)',
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 3),
        decoration: BoxDecoration(
          color: (isApi ? AppColors.torchGold : AppColors.stoneMid)
              .withValues(alpha: 0.18),
          borderRadius: BorderRadius.circular(6),
          border: Border.all(
            color: (isApi ? AppColors.torchGold : AppColors.stoneMid)
                .withValues(alpha: 0.5),
            width: 1,
          ),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              isApi ? Icons.auto_awesome : Icons.menu_book_outlined,
              size: 11,
              color: isApi ? AppColors.torchGold : AppColors.textLight,
            ),
            const SizedBox(width: 3),
            Text(
              isApi ? 'Live' : 'Classic',
              style: TextStyle(
                fontSize: 10,
                fontWeight: FontWeight.w600,
                color: isApi
                    ? AppColors.torchGold
                    : AppColors.textLight.withValues(alpha: 0.7),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
